### ISSUE TITLE
No fid_evaluation.py file present

### ISSUE THREAD

**Issue by adheshgarg** [Xuanmeng-Zhang/MVCGAN#1]
Hi I was trying to run the project as part of my college project but I noticed that fid_evaluation.py file is missing and the file in the pi_gan repo is of a different version perhaps since function have different declarations. Can you please help?

**Comment by Xuanmeng-Zhang** [comment]
Hi Adhesh, thanks for pointing out this issue. I have uploaded the [evaluation file](https://github.com/Xuanmeng-Zhang/MVCGAN/blob/main/fid_evaluation.py).
Specifically, you can first save the rendered images in the directory and then use the [evaluation file](https://github.com/Xuanmeng-Zhang/MVCGAN/blob/main/fid_evaluation.py) to compute the fid distance between generated images and real images.

**Comment by xingyi-li** [comment]
Hi, @Xuanmeng-Zhang. 
Thanks for sharing the fid_evaluation.py file. However, in the main.py, some implementations from fid_evaluation.py are still missing:
```python
fid_evaluation.output_images(alpha, generator_ddp, metadata, rank, world_size, generated_dir)
fid = fid_evaluation.calculate_fid(metadata['dataset'], generated_dir, opt.eval_dir, target_size=metadata['output_size'])
```

**Comment by Xuanmeng-Zhang** [comment]
Hi xingyi,  thank you for letting me know this. Now [calculate_fid](https://github.com/Xuanmeng-Zhang/MVCGAN/blob/007270104db723b7781e684e534095e7e86e89df/fid_evaluation.py#L41) is added in the file.

**Comment by xingyi-li** [comment]
Hi @Xuanmeng-Zhang, thanks for adding `calculate_fid`, but `output_images` is still missing :-).

**Comment by Xuanmeng-Zhang** [comment]
Hi @xingyi-li, please refer to [output_images](https://github.com/Xuanmeng-Zhang/MVCGAN/blob/b1f921ba2569d3c9a87ec5f7d15979ac1f7b7d4f/fid_evaluation.py#L51).

**Comment by universome** [comment]
Hi @Xuanmeng-Zhang ! Thank you for your work and the update, but the FID evaluation still has some issues:
- [calculate_fid(...)](https://github.com/Xuanmeng-Zhang/MVCGAN/blob/main/fid_evaluation.py#L77) takes 3 arguments as input
- [4 arguments are being passed in `main.py`](https://github.com/Xuanmeng-Zhang/MVCGAN/blob/main/main.py#L487)
And the training script fails at this line

**Comment by Xuanmeng-Zhang** [comment]
Hi @universome, thank you for letting me know this.  I have updated the function [calculate_Fid](https://github.com/Xuanmeng-Zhang/MVCGAN/blob/465d8191d887ac744c52ee57052de08e8ea20d92/fid_evaluation.py#L77).
